### ISSUE TITLE
Team Work Contract

### ISSUE THREAD

**Issue by rahulkuriyedath** [UBC-MDS/dsci522-group16#1]
Feel free to use this issue to add points that you would like to include in the Team Work Contract.

**Comment by IfyAnene7** [comment]
- Let everyone know beforehand if you absolutely can't make it to a meeting.
- Let everyone know beforehand if you cannot meet a deliverable. 
- I guess the previous two points just alludes to early/on time and effective communication.

**Comment by Saule-Atymtayeva** [comment]
- Take into consideration the timezones of all team members when scheduling meetings and discussions.
- Be respectful towards each other (I think, it's obvious 🙂).
- Everyone tries to be useful to the team and the common goal.
- If someone has any difficulties, they should ask for help the rest team members.
- Saule's usual working time: from 8 pm to 8 am Vancouver time.

**Comment by Saule-Atymtayeva** [comment]
The last version of Team Work Contract so far:
- Be respectful towards each other.
- Everyone tries to be useful to the team and the common goal.
- If someone has any difficulties, they should ask for help the rest team members.
- Take into consideration the timezones of all team members when scheduling meetings and discussions.
- Let everyone know beforehand if you absolutely cannot attend a meeting.
- Let everyone know beforehand if you cannot meet a deliverable.
- Aditya's usual working time: 11:00 am to 12 am Vancouver time.
- Ify's usual working time: 8:00 am to 9:00 pm Vancouver time.
- Saule's usual working time: 8:00 pm to 8:00 am Vancouver time.
- Rahul's usual working time: 8:30 pm to 8:00 am Vancouver time.

**Comment by rahulkuriyedath** [comment]
Hi @Saule-Atymtayeva , My usual working time would be: 8:30pm to 8:00am Vancouver time

**Comment by IfyAnene7** [comment]
Hi @Saule-Atymtayeva , my usual working time would be: 8:00 am to 9:00 pm Vancouver time
