### ISSUE TITLE
Proposing organized approach

### ISSUE THREAD

**Issue by adibns** [UBC-MDS/dsci522-group16#18]
Hi @IfyAnene7 @Saule-Atymtayeva @rahulkuriyedath 

I am proposing following changes to our approach towards project

1. Call on Tuesday morning  8 AM Indian Time i.e., Tuesday 8:30 AM Khazak time and Monday 9:30 PM Toronto Time. The discussion would be regarding milestone expectations, work sharing and internal team deadlines (with meeting time flexibility and workload sharing whenever/wherever necessary)

2.  A call on Thursday evening 7 PM IST i.e., 7:30 PM Khazak TIme and 8:30 AM Toronto Time. The discussion would be regarding the progress. Each team mate will walk through their work comprehensively. Team will compare milestone expectations and current work and propose changes if necessary and also help if someone is stuck.

3.  There might be dependencies in the milestone, like Point 3 can be started only if point 2 and point 1 are completed. The team member free till Thursday's call will reach out to instructor / TA to confirm if we are on the right direction and share it to everyone here on GitHub as an Issue (If the person free is unable to do the job due to considerable problems, someone in the team will take that charge based on time availability. If no one has time I will take things up)

4.  A call on Saturday evening 7 PM IST i.e., 7:30 PM Khazak TIme and 8:30 AM Toronto Time. Work added after second call would be walked through comprehensively by each team member. Only, if team has majority/ full consensus about work of each other we will push the changes to GitHub.com. If not we can ask TA's/Instructors for clarifications and proceed.

5. All other things will be taken care of as situations arise. 

Please let me know your thoughts and let me know if we could add or remove something.

**Comment by Saule-Atymtayeva** [comment]
Everything is fine! And if a team member cannot participate in an arranged meeting due to some reasons, he or she should let others know about that.
