### ISSUE TITLE
Errors in README.md in the src directory

### ISSUE THREAD

**Issue by IfyAnene7** [UBC-MDS/dsci522-group16#27]
- Filenames in usage of download_data.py and generate_data.py do not have valid file extensions.

- Parameter names are wrong in usage for download_data.py. Only inputs should be the url and complete path of the csv which we want to write.

- There is no script called generate_data.py, it should instead be split_train_test.py

- Usage for generate_figs.py does not have ‘python’ command

- Typo in usage of fit_cancer_prediction.py

**Comment by Saule-Atymtayeva** [comment]
Moreover, some libraries are needed to be added in the yml file.

**Comment by IfyAnene7** [comment]
Done!
