### ISSUE TITLE
Problem statement for the project

### ISSUE THREAD

**Issue by rahulkuriyedath** [UBC-MDS/dsci522-group16#3]
@adibns , @IfyAnene7 , @Saule-Atymtayeva 

I feel we should define the question that we are looking to answer as:
"How has production in wheat and rice varied with increase in population worldwide?"
This could be our main focus. 

Along with this, we could also add functionality to visualize for various countries. i.e. We can select a country and it will show a graph of how production has varied over time overlayed with how population has increased for that country. 

What do you guys think?

**Comment by rahulkuriyedath** [comment]
On second thought, I think we should focus on one continent rather than the whole world since it would be easier to fetch data for one continent. I downloaded the data for Asia (link: http://fenixservices.fao.org/faostat/static/bulkdownloads/Production_Crops_E_Asia.zip ) and it seems that there is data only for 37 countries while there are 48 countries in Asia. We might need to be careful when plotting population vs yield. 

Would love to hear what you all think

**Comment by IfyAnene7** [comment]
I'm leaning towards keeping it simple and asking a simple inferential/predictive question. So looking at the data, we have, I think we can ask a predictive question such as "How many tonnes of Maize/Wheat(whatever) will be produced in 2019?"

**Comment by Saule-Atymtayeva** [comment]
Rahul, I would agree with Ify. Let's make it a predictive question. We could select the three largest Asian (from your file) any crop (let's say wheat) producing countries and show predictions for them. Before that, we could plot the amount of the annually produced crop for each country.
