### ISSUE TITLE
Student Feedback (From Chad)

### ISSUE THREAD

**Issue by ChadNeald** [UBC-MDS/dsci522-group16#36]
Hey there Group 16! 

I wanted to give you all this feedback as soon as possible so you wouldn't be stressed out last minute. First off I just wanted to say great job! I was able to understand what the goal of the project was immediately and everything was documented very clearly throughout the scripts and the report. I walked through all the directories and found that everything was ordered and structured in a logical manner. Below are my thoughts on some things that could potentially help improve the project!

- In terms of the REAME file, I think it would be helpful to readers to include a quick explanation of what "anthropometric data" is since it comes up a lot in the project. A lot of people like myself without the background knowledge might not know what that is right away.  The README also eludes to a best classifier being chosen but it never actually says what that classifier is. I found out from the report, but I think the readme should be able to give a nice overview of the entire project and explicitly say which classifier was chosen.

- In the src directory there is an EDA0.ipynb file that seems like it shouldn't be there? Maybe it's a first draft of your project? Either way I feel that should be removed now.

- Regarding the final report, there are 3 plots that show the most promising features, but then it says that the model was fit on all of the numeric features. Maybe in the analysis section you could talk about whether or not you tried using only these features or if you attempted to drop features but it resulted in a worse recall score etc. I think a bit more elaboration on why all features were chosen in the end would add some clarity to the process. Or if there wasn't time for this analysis, maybe it could go under a section of what you would explore if you had more time.

Well I wrote a lot but I think the first 2 are quick fixes so I hope it's not too much to think about before our final quizzes next week! Again great job on everything you're crushing it!

**Comment by IfyAnene7** [comment]
Thank you so much for the feedback @ChadNeald!
