### ISSUE TITLE
Peer Feeback - Lara

### ISSUE THREAD

**Issue by larahabashy** [UBC-MDS/dsci522-group16#43]
Hi classmates, great effort on the project and neat selection of data! The project is very well done.

Here's my feedback:

- **Documentation**: Functions and code are very well-documented with comments throughout.
- **Code**: Easily readable and reproducible. 

- **Analysis and reasoning**: Overall clear and sufficient analysis. Great flow of reasoning. 

- **Communication**: I found some tiny typos in your report under Analysis. The words "initial" and "conjunction" are misspelt. <br> I would also suggest making the size of the table "Cross-validation results for different classifiers" smaller.  <br> The improvements section is a great addition to your report!

- **Suggestions**:
I would consider moving figures generated by running make all to results subfolder called `figures`, essentially splitting results into `figures` and a subfolder called `predictions`. <br> I would also suggest keeping only one EDA file in src directory. <br> I noticed the link referring to `literal document` in the README file does not link to the report in doc folder.

**Comment by IfyAnene7** [comment]
Thank you so much @larahabashy!!!
