### ISSUE TITLE
Milestone 1 Tasks

### ISSUE THREAD

**Issue by rahulkuriyedath** [UBC-MDS/dsci522-group16#5]
Hi @adibns , @IfyAnene7 , @Saule-Atymtayeva 

Based on our discussion, the main question that we are interested in answering in this project is :- 

> How has production in paddy and wheat in Asia varied over time with change in population ?

Below are the tasks that we'll be working on:-

Rahul and Aditya :-
- Work on integrating docopt with code to download the zip files, unzip them and place them in "/data/raw/" folder.

Saule and Ify :- 
- Start with EDA on the datasets from the FAO and World bank websites.

I will also work on creating the contrib file for the project. 

Please let me know if my understanding is wrong or if any changes are required.

**Comment by IfyAnene7** [comment]
Everything looks good, and this was a brilliant idea. It really helps keep me in check of what I have to do. Things I was able to accomplish:

- Created a gitignore file.
- created an EDA literate code document (ipynb) in the src subdirectory. 
- created a readme file that gives instructions on how to navigate the src folder. 
- I also noticed that fetch_file.py was not in an appropriate folder (src), so I wanted to highlight this.

**Comment by adibns** [comment]
@IfyAnene7  I had issues with pushing changes from my local. Rahul asked for code and for temporary purpose fetch file was uploaded in the main branch.

Changes would be made

**Comment by adibns** [comment]
@IfyAnene7 fetch-file.py has been relocated to src with new name fetch-file-wip.py

**Comment by IfyAnene7** [comment]
Just created a pull request that adds a description of the proposed project analysis. Can anyone else who sees this review it, please and thank you.

**Comment by IfyAnene7** [comment]
Can someone add to the usage subsection just as Tiff did here => https://github.com/ttimbers/breast_cancer_predictor/tree/v1.1 is there any other thing we're meant to do?
